### ISSUE TITLE
Infinity reduplication process in the flux's capacitors terminal conjunction system. 

### ISSUE THREAD

**Issue by antoniwan** [khalifenizar/ironhack-week-3-examples-jan-2016#1]
Several questions accompany this issue, @khalifenizar.

How does the quantum description of reality, which includes elements such as the superposition of states and wavefunction collapse or quantum decoherence, give rise to the reality we perceive?
- Another way of stating this is the measurement problem – what constitutes a "measurement" which causes the wave function to collapse into a definite state? 
- Unlike classical physical processes, some quantum mechanical processes (such as quantum teleportation arising from quantum entanglement) cannot be simultaneously "local", "causal" and "real", but it is not obvious which of these properties must be sacrificed or if an attempt to describe quantum mechanical processes in these senses is a category error that doesn't even make sense to talk about if one properly understands quantum mechanics.

Why did the universe have such low entropy in the past, resulting in the distinction between past and future and the second law of thermodynamics?
- Why are CP violations observed in certain weak force decays, but not elsewhere?
- Are CP violations somehow a product of the Second Law of Thermodynamics, or are they a separate arrow of time? Are there exceptions to the principle of causality?
- Is there a single possible past?
- Is the present moment physically distinct from the past and future or is it merely an emergent property of consciousness?
- Why does time have a direction?
- What links the quantum arrow of time to the thermodynamic arrow?

Is there a theory which explains the values of all fundamental physical constants?
- Is the theory string theory?
- Is there a theory which explains why the gauge groups of the Standard model are as they are, why observed spacetime has 3 spatial dimensions and 1 temporal dimension, and why all laws of physics are as they are?
- Do "fundamental physical constants" vary over time?
- Are any of the particles in the standard model of particle physics actually composite particles too tightly bound to observe as such at current experimental energies?
- Are there fundamental particles that have not yet been observed, and, if so, which ones are they and what are their properties?
- Are there unobserved fundamental forces implied by a theory that explains other unsolved problems in physics?

**Additionally**

Why does the zero-point energy of the vacuum not cause a large cosmological constant? What cancels it out?

Finally, I've attached a screenshot of the hardware running these systems. Please let me know if there's something that ironhack-week-3-examples-jan-2016's maintenance team can do to help us out.

![Flux capacitor's energy matrix](http://i.imgur.com/DFlmzvK.jpg)

**Comment by cyberkiko** [comment]
:+1:

**Comment by jonathantorres** [comment]
+1

**Comment by nizaroni** [comment]
:hankey:
